import {
  UserOutlined,
  FileTextOutlined,
  PhoneOutlined,
  MessageOutlined,
  GlobalOutlined,
  EnvironmentOutlined,
  DatabaseOutlined,
  CalendarOutlined,
} from "@ant-design/icons";

// Profile data templates organized by categories
export const PROFILE_DATA_TEMPLATES = [
  // Personal Information
  {
    name: "Nama Lengkap",
    field: {
      key: "name",
      label: "Nama Lengkap",
      required: true,
      type: "text",
      placeholder: "Masukkan nama lengkap",
    },
    category: "personal",
    icon: UserOutlined,
    description: "Nama lengkap pengguna",
  },
  {
    name: "Nomor Identitas",
    field: {
      key: "personal_id",
      label: "Nomor Identitas",
      required: false,
      type: "text",
      placeholder: "Masukkan nomor identitas",
    },
    category: "personal",
    icon: FileTextOutlined,
    description: "Nomor identifikasi pribadi",
  },
  {
    name: "Jenis Kelamin",
    field: {
      key: "gender",
      label: "Jenis Kelamin",
      required: true,
      type: "select",
      placeholder: "Pilih jenis kelamin",
      options: [
        { label: "Laki-laki", value: "M" },
        { label: "Perempuan", value: "F" },
      ],
    },
    category: "personal",
    icon: UserOutlined,
    description: "Pemilihan jenis kelamin",
  },
  {
    name: "Tanggal Lahir",
    field: {
      key: "birth_date",
      label: "Tanggal Lahir",
      required: false,
      type: "date",
      placeholder: "Pilih tanggal lahir",
    },
    category: "personal",
    icon: CalendarOutlined,
    description: "Tanggal lahir pengguna",
  },

  // Contact Information
  {
    name: "WhatsApp",
    field: {
      key: "whatsapp",
      label: "WhatsApp",
      required: false,
      type: "text",
      placeholder: "Masukkan nomor WhatsApp",
    },
    category: "contact",
    icon: PhoneOutlined,
    description: "Nomor kontak WhatsApp",
  },
  {
    name: "Line",
    field: {
      key: "line",
      label: "Line",
      required: false,
      type: "text",
      placeholder: "Masukkan ID Line",
    },
    category: "contact",
    icon: MessageOutlined,
    description: "ID Line",
  },
  {
    name: "Instagram",
    field: {
      key: "instagram",
      label: "Instagram",
      required: false,
      type: "text",
      placeholder: "Masukkan username Instagram",
    },
    category: "contact",
    icon: GlobalOutlined,
    description: "Username Instagram",
  },
  {
    name: "TikTok",
    field: {
      key: "tiktok",
      label: "TikTok",
      required: false,
      type: "text",
      placeholder: "Masukkan username TikTok",
    },
    category: "contact",
    icon: GlobalOutlined,
    description: "Username TikTok",
  },
  {
    name: "LinkedIn",
    field: {
      key: "linkedin",
      label: "LinkedIn",
      required: false,
      type: "text",
      placeholder: "Masukkan profil LinkedIn",
    },
    category: "contact",
    icon: GlobalOutlined,
    description: "URL profil LinkedIn",
  },

  // Location Information
  {
    name: "Provinsi Domisili",
    field: {
      key: "province_id",
      label: "Provinsi Domisili",
      required: false,
      type: "select",
      placeholder: "Pilih provinsi domisili",
    },
    category: "location",
    icon: EnvironmentOutlined,
    description: "Provinsi tempat tinggal sekarang",
  },
  {
    name: "Kota Domisili",
    field: {
      key: "city_id",
      label: "Kota Domisili",
      required: false,
      type: "select",
      placeholder: "Pilih kota domisili",
      helpText: "Pilih provinsi domisili terlebih dahulu.",
    },
    category: "location",
    icon: EnvironmentOutlined,
    description: "Kota tempat tinggal sekarang",
  },
  {
    name: "Negara Domisili",
    field: {
      key: "country",
      label: "Negara Domisili",
      required: false,
      type: "select",
      placeholder: "Pilih negara domisili",
    },
    category: "location",
    icon: EnvironmentOutlined,
    description: "Negara tempat tinggal sekarang",
  },
  {
    name: "Provinsi Asal",
    field: {
      key: "origin_province_id",
      label: "Provinsi Asal",
      required: false,
      type: "select",
      placeholder: "Pilih provinsi asal",
    },
    category: "location",
    icon: EnvironmentOutlined,
    description: "Provinsi asal daerah",
  },
  {
    name: "Kota Asal",
    field: {
      key: "origin_city_id",
      label: "Kota Asal",
      required: false,
      type: "select",
      placeholder: "Pilih kota asal",
      helpText: "Pilih provinsi asal terlebih dahulu.",
    },
    category: "location",
    icon: EnvironmentOutlined,
    description: "Kota asal daerah",
  },

  // Education Information
  {
    name: "Riwayat Pendidikan",
    field: {
      key: "education_history",
      label: "Riwayat Pendidikan",
      required: false,
      type: "education_history",
      placeholder: "",
    },
    category: "education",
    icon: DatabaseOutlined,
    description: "Daftar lengkap riwayat pendidikan (jenjang, kampus, jurusan, tahun masuk)",
  },
  {
    name: "Pendidikan Sekarang",
    field: {
      key: "current_education",
      label: "Pendidikan Sekarang",
      required: false,
      type: "current_education",
      placeholder: "",
    },
    category: "education",
    icon: DatabaseOutlined,
    description: "Input pendidikan sekarang (jenjang, kampus, jurusan, tahun masuk)",
  },
] as const;
