export const permissionLabels: Record<string, string> = {
  "courses.read": "Melihat kelas dan progres peserta",
  "courses.manage": "Mengelola kelas dan materi pembelajaran",
  "dashboard.read": "Melihat ringkasan dasbor",
  "admin_users.read": "Melihat akun admin",
  "admin_users.manage": "Mengelola akun dan akses admin",
  "rbac.read": "Melihat daftar peran dan hak akses",
  "tickets.review": "Meninjau permintaan akses",
  "members.read": "Melihat data anggota",
  "members.manage": "Mengelola data anggota",
  "members.credentials.manage": "Mengubah email dan kata sandi anggota",
  "activities.read": "Melihat kegiatan",
  "activities.manage": "Mengelola kegiatan",
  "activities.publish": "Menayangkan kegiatan atau mengembalikannya ke draf",
  "activities.registration.manage": "Membuka dan menutup pendaftaran kegiatan",
  "activity_registrations.read": "Melihat pendaftaran kegiatan",
  "activity_registrations.manage": "Mengelola pendaftaran kegiatan",
  "activity_registrations.export": "Mengekspor data pendaftaran kegiatan",
  "counseling.read": "Melihat data Ruang Curhat",
  "counseling.manage": "Mengelola layanan Ruang Curhat",
  "achievements.read": "Melihat prestasi anggota",
  "achievements.review": "Meninjau pengajuan prestasi",
  "achievements.export": "Mengekspor data prestasi",
  "leaderboards.read": "Melihat peringkat anggota",
  "reference_data.manage": "Mengelola data referensi",
  "clubs.read": "Melihat klub",
  "clubs.manage": "Mengelola klub",
  "club_registrations.read": "Melihat pendaftaran klub",
  "club_registrations.manage": "Mengelola pendaftaran klub",
  "club_registrations.export": "Mengekspor data pendaftaran klub",
  "custom_forms.read": "Melihat formulir digital",
  "custom_forms.manage": "Mengelola formulir digital",
  "certificate.template.read": "Melihat templat sertifikat",
  "certificate.template.manage": "Mengelola templat sertifikat",
  "certificate.read": "Melihat sertifikat",
  "certificate.issue": "Menerbitkan sertifikat",
  "certificate.approve": "Menyetujui sertifikat sebagai penandatangan",
  "certificate.revoke": "Mencabut sertifikat",
};
